### ISSUE TITLE
[Announcement] Homework 3 is out (+ pizza party poll)

### ISSUE THREAD

**Issue by hyunsukimsokcho** [prosyslab-classroom/is593-2022-spring#12]
Here is the invitation link for the homework:

- Homework 3: https://classroom.github.com/a/yVTu6_Zv (due: **23:59:59, Apr. 14**)

One shall submit a reading critique for the [article](https://cacm.acm.org/magazines/2021/7/253452-formal-software-verification-measures-up/fulltext) published in CACM 2021.
For submission, please find the **Reading Critique 3** slot in Gradescope and submit a pdf file.

---

As notified in the class, we will throw a **pizza party** for lunch after the midterm presentations (Apr. 19). RSVP to the poll to figure out the pizza demands:
- Pizza party poll: https://forms.gle/4eyjQBcsgKKecw7M7 (due: **23:59:59, Apr. 7**)

**Comment by AnHaechan** [comment]
I cannot open the google form for the pizza party. It says

```
You need permission
This form can only be viewed by users in the owner's organization.

Try contacting the owner of the form if you think this is a mistake. [Learn More.](https://support.google.com/docs/?p=forms_settings)
```

**Comment by hyunsukimsokcho** [comment]
Now fixed. Thanks:)
