### ISSUE TITLE
[Announcement] Homework 4 is out

### ISSUE THREAD

**Issue by hyunsukimsokcho** [prosyslab-classroom/is593-2022-spring#18]
Here is the invitation link for the homework:

- Homework 4: https://classroom.github.com/a/Xyn1Z3kz (due: **23:59:59, Apr. 28**)

One shall implement a program verifier that automatically checks non-trivial semantic properties with z3 by extracting CHC formulae.

**Comment by p51lee** [comment]
I tried to run the code, but I got the following error.
```
Illegal head. The head predicate needs to be uninterpreted and registered (as recursive)
(or
    (if.then (:var 2) (:var 1) (:var 3) (:var 0))
    (not (> (:var 3) 10))
    (not entry)
    (not (> (:var 3) 1)))
```
What does the message *"The head predicate needs to be uninterpreted and registered (as recursive)"* mean?

**Comment by KihongHeo** [comment]
Hi,
Next time please make a new issue for your question.

Each rule consists of "head" and "body". For example,
```
x = 1 /\ y = x => if.then(x, y)
```
here `x = 1 /\ y = x` is the body and `if.then(x, y)` is the head of this rule.

There are some restrictions in CHC. One basic thing is that the head should only contain one literal (so is horn clause).
I think, in your example, the head contains `or` so this is not a valid horn clause. 
Please think more why you need `or` for this rule and why horn clause is enough to encode the semantics for this assignment.

**Comment by p51lee** [comment]
It worked after I changed the Horn clause from disjunction form to implication form. Thank you!
