### ISSUE TITLE
[Question][Hw4] Allowed instructions in the input programs

### ISSUE THREAD

**Issue by AnHaechan** [prosyslab-classroom/is593-2022-spring#22]
Hi,

I'd like to ask which subset of LLVM instructions should we consider to exist in the input programs.
In the provided examples(`example1.ll` to `example5.ll`),
the kind of instructions are limited to the followings:
```
      | Llvm.Opcode.Br 
      | Llvm.Opcode.Call
      | Llvm.Opcode.ICmp
      | Llvm.Opcode.ZExt
      | Llvm.Opcode.PHI 
      | Llvm.Opcode.Add
      | Llvm.Opcode.Ret
```
Can I only consider those instructions?

Thank you.

**Comment by hyunsukimsokcho** [comment]
Additionally, you should be able to handle every binary operations for integers (`+`, `-`, `*`, `/`) as the values are all integers in the allowed programs.
