### ISSUE TITLE
[Question][Final Project] Proposal in korean

### ISSUE THREAD

**Issue by p51lee** [prosyslab-classroom/is593-2022-spring#25]
For korean students, is it necessary to write a proposal in korean?

**Comment by KihongHeo** [comment]
Yes.

**Comment by KihongHeo** [comment]
Oh. I am sorry. As originally announced, English.

**Comment by silee-k** [comment]
Can we submit it in Korean first and modify it in English later?

**Comment by KihongHeo** [comment]
For someone who got confused because of that, let me give all of you one more day. All submissions must be in English.
