### ISSUE TITLE
[Question][Final] Ill-formed final proposal

### ISSUE THREAD

**Issue by workstudy-zero** [prosyslab-classroom/is593-2022-spring#27]
Hello, I'm Jaeho Choi (20223684).

I noticed that my proposal is ill-formed. I just realized that there is a specified format for the proposal.
Should I rewrite the proposal and submit it?

Sorry for the inconvenience.

**Comment by workstudy-zero** [comment]
Thank a lot! I'll resubmit it by tonight.

**Comment by AnHaechan** [comment]
Professor, I've also found out that my submission was not using the right format too. I'll re-submit by today. Thanks.
