### ISSUE TITLE
[Question][Hw0] correctness of test in `satTest.ml`

### ISSUE THREAD

**Issue by AnHaechan** [prosyslab-classroom/is593-2022-spring#3]
Hi, 

The `"test 2"` of `satTest.ml` can fail even if `sat.ml` has been correctly implemented.
It expects `(SAT (false, false, false))` as the return value for `solve (And (Or (Z, Not Y), Or (Not X, Not Z)))`.
However, since `(SAT (true, false, false))` is also a satisfying assignment for the given formula, the test is not correct.
I think it should be fixed to allow any satisfying assignments for given formula since there was no specification of this issue in the problem description.

Thanks.

**Comment by hyunsukimsokcho** [comment]
Yes, you are right. For now, in the test script, consider the test passes if both are `SAT` or `UnSAT`.
