### ISSUE TITLE
[Question][Hw1] About Submission

### ISSUE THREAD

**Issue by KAIST-JongchanPark** [prosyslab-classroom/is593-2022-spring#4]
I only submitted my pdf file to Gradescope, not pushed it into my github repository.

Is it okay?

**Comment by KihongHeo** [comment]
No problem.

**Comment by AnHaechan** [comment]
@KihongHeo I only have submitted on github repository. Is it also ok?

**Comment by KihongHeo** [comment]
No problem. But can you submit your pdf via Gradescope?

Next time we will announce more clearly.

**Comment by AnHaechan** [comment]
Yes, thanks!
