### ISSUE TITLE
[Announcement] submission

### ISSUE THREAD

**Issue by KihongHeo** [prosyslab-classroom/is593-2022-spring#5]
Hi all,

Please submit your homework 1 to Gradescope. Only 12/14 have been submitted so far. 

Sorry for the confusion. Next time, we will clarify the submission process.

**Comment by qqor** [comment]
Sorry for the late check, but the submission in Gradescope seems to be closed as it was until 3/14 12:00 AM. Is there still a way to submit my file through Gradescope?

**Comment by KihongHeo** [comment]
Reopened.
