### ISSUE TITLE
[Question][Midterm Project] Due date for grading

### ISSUE THREAD

**Issue by AnHaechan** [prosyslab-classroom/is593-2022-spring#9]
According to this [document](https://docs.google.com/document/d/14IsEdXPdWaGko7XB3rYdkcFLs1C47qnLQqMT_wQygqY/edit#), the midterm project has two due dates(April 1st and 4th).

Will the grade for already-provided test cases be detertmined at first due date or second due date(altogether with student-provided test cases)?

Thanks.

**Comment by hyunsukimsokcho** [comment]
After the first due date (Apr. 1st), we will update the test cases in Gradescope but not publicize it.

What do you mean by the **already-provided** test cases? I cannot clearly see your concerns.

**Comment by AnHaechan** [comment]
I mean, there are two kinds of test cases.
**First**, the test cases already in our repository.
**Second**, the test cases (that will be) submitted by students.

When grading the final score, will the **first** test cases be evaluated based on our synthesizer submitted at April 1st OR the one submitted at April 4th?

**Comment by hyunsukimsokcho** [comment]
The latter, it is (see Rule 5).
